### ISSUE TITLE
On Save doesn't work for Atom 1.16.0-beta 0

### ISSUE THREAD

**Issue by pingshunhuangalex** [lysyi3m/atom-postcss-sorting#28]
Hi @lysyi3m 
1. I just found out that `on save` wouldn't work for my Atom beta. The weird thing is notification will still show,  but there is just no change in my CSS. On the other hand, the command does work like a charm...

2. Another problem is that it can't recognise the `post-sorting.json` file I dropped in my HOME `~/`. If I check the ``check for config file` option, the whole package just stops working regardless the already existing json file.

3. It would be nice if you can add a preset for `google` which requires an alphabetical declaration sort without prefix (optional if you are busy)

Thanks.

**Comment by pingshunhuangalex** [comment]
Any updates on this please? @paweljedrzejczyk @lysyi3m

**Comment by lysyi3m** [comment]
Hello, @pingshunhuangalex 

Thank you for your report. I've just released [v2.10.0](https://github.com/lysyi3m/atom-postcss-sorting/releases/tag/v2.10.0) with fixed about the issue you mentioned.

1. "On save" is currently working as expected (tested on stable 1.15.0 and beta 1.16.0-beta0)

2. At first, as described in [`README.md`](https://github.com/lysyi3m/atom-postcss-sorting/tree/v2.9.0#options) file of v2.9.0 version, config file under your `HOME` directory should be named `postcss-sorting.json` and NOT `.postcss-sorting.json`. But. To prevent any confusing there is no such restrictions from v2.10.0 (see updated [`README.md`](https://github.com/lysyi3m/atom-postcss-sorting/blob/master/README.md))

3. There are some cons in "new google preset" feature.  Firstly, Google (_company_) doesn't have its own CSS sorting rules, methodology or any "best practices for writing CSS". Secondly, `atom-postcss-sorting` plugin was build on top of [`postcss-sorting`](https://github.com/hudochenkov/postcss-sorting) plugin, which doesn't provide any `google` preset. Thirdly, sorting CSS rules alphabetically is a very controversial decision, because `postcss-sorting` (inspired by `CSSComb`) rules are based on "web developer's judgment in ordering CSS styles" (c), and "alphabetical" order is not useful in real world, IMO. Also, for someone who really wants to sort his stylesheets in that way, there is "Custom config path" options included out of the box.

Btw, since this is an open source plugin better to do not panic if repo *maintainer* (not *maintainer**s***) doesn't respond immediately.  Especially if this is not high-priority bug. It's better to try resolve issue and create PR with possible solution.

You could try latest [v2.10.0](https://atom.io/packages/postcss-sorting) version of the plugin. If your issue hasn't been fixed, feel free to reopen this issue.

Cheers 🍻

**Comment by pingshunhuangalex** [comment]
Thanks @lysyi3m so much for fixing it up. I tested it up, and it works like a charm.

Sorry, I got a bit panic cuz this package is kind of my everyday-used one. I do understand it takes a great amount of effort for developers like yourself to keep the open source plugin alive on top of your busy like, and I do want to apologise for being a bit "pushy". For the record, I did try to dig into the code and resolve the issue myself, but got no luck probably due to my limited skills there.

Meanwhile, I tried to sort things alphabetically using `atom-sort` and realised it's actually not very useful as you pointed out. I thought I just got carried away by this [Google Style Guidelines thing](https://google.github.io/styleguide/htmlcssguide.html#HTML_Style_Rules)

Finally, I do want to point out that if I enabled other packages which also happen to have an `on save` option (like `autoprefixer`), it'll beat `postcss-sorting` to it which renders this plugin not working again. I'm not sure if this can be fixed as it's not actually an issue. I've already solved it by writing my own `composed command` with a `setTimeout`, so if you can't think of a better idea, please just leave it.

Thanks again for fixing the issue and keep the plugin alive :)
